"""포트별 가짜 구현 — usecase 테스트 주입용 (덕타이핑, Protocol 상속 불필요).
domain 테스트(tests/unit/)는 순수 함수라 fakes조차 필요 없다.
"""
# W2.5+
class FakeLLM: ...
class FakeEmbedder: ...
class FakeVectorIndex: ...
class FakeGraph: ...
class FakeTracer:
    def emit(self, event): pass
